### ISSUE TITLE
Disk space full - Potential logging problem

### ISSUE THREAD

**Issue by richardhallett** [datacite/datacite#1019]
The containers appear to be able to get full of error logs, Fargate allows 10gb per docker container, however it's possible we have too many noisy things causing this to be an issue.

One possibility is that application logs go directly to nginx error.log on disk within container. This is visible on the local system by:
1) Access your docker container
2) Cause an app error (e.g. 404 for repository)
3) Notice /var/log/nginx/error.log contains app messages.

They should only go to cloudwatch.

**Comment by mfenner** [comment]
This has been fixed.

**Comment by richardhallett** [comment]
This needs some additional investigation, it seems it's still occuring at least within Bracco specifically.

I suggest next piece of work is to investigate the bracco docker build and see what is being put into the container.

**Comment by mfenner** [comment]
@richardhallett For `datacite/bracco` specifically, haven't we decided to move away from Docker and run it as single-page app?

**Comment by richardhallett** [comment]
Uncertain on the decision, but we can certainly look at that, it would solve this issue.

**Comment by richardhallett** [comment]
This has been solved by moving away from docker container for bracco.
